name: Java CI
on: [push]

jobs:
  jenkins-container-pipeline:
    runs-on: self-hosted
#    container:
 #     image: ghcr.io/jenkinsci/jenkinsfile-runner:master --- drugi kontejner ??
    steps:
      - uses: actions/checkout@v2
  #    - uses: jenkinsci/jfr-container-action@master
      - uses: jenkinsci/jfr-static-image-action@master
        with:
          command: run
          jenkinsfile: Jenkinsfile
          pluginstxt: plugins.txt
          jcasc: jcasc.yml
      - name: Whoami
        run: whoami
